// <auto-generated />
namespace ControloAvenca1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dez : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dez));
        
        string IMigrationMetadata.Id
        {
            get { return "202103171531062_dez"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
